apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepcheap-app
spec:
  selector:
    matchLabels:
      app: deepcheap-app
  template:
    metadata:
      labels:
        app: deepcheap-app
    spec:
      containers:
      - name: deepcheap-app
        image: deepcheap-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: deepcheap-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  selector:
    app: deepcheap-app