apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: deepcheap-app
build:
  artifacts:
  - image: deepcheap-app
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
